### ISSUE TITLE
Collect build time stats

### ISSUE THREAD

**Issue by nikic** [kwk/llvm-daily-fedora-rpms#47]
The snapshot build have become substantially slower at some point, but it's currently hard to analyze why/when this happened.

It would be nice to have a way to collect and graph the build times over time.

Not entirely sure what the best way to do this is -- a starting point would be just a one-off script to collect stats for all the incubator coprs that are still alive. For long-term tracking we would have to store the data once it becomes no longer available.

**Comment by kwk** [comment]
Round about a year ago I collected statistics from the LLVM buildbots using a naive approach. I kept the embarrassing project here https://github.com/kwk/llvm-snapshot-monitoring .  But in theroy we could borrow ideas like the Grafana provisioning from there. I never continued to work on this because I felt it was overkill but I still kind of liked the idea of a nicely packed up GUI and data for evaluation. I'm sure getting copr stats is doable as well. Let me ask around.

**Comment by kwk** [comment]
I recall that there are daily db dumps from copr that could be consumed: https://copr.fedorainfracloud.org/db_dumps/

**Comment by kwk** [comment]
I'll just print a diagram for the last 32 or so days with the build time on the y-axis, the date on the x-axis and a color representing a failed or succeeded build. I'll create such a diagram for each package. Each diagram will have multiple entries for each day representing the different chroots. We can look back a certain amount of time because the incubator projects are only deleted after [32 days](https://github.com/kwk/llvm-daily-fedora-rpms/blob/e69b8c48ca249b4078755c835a11d804039d495e/.github/workflows/fedora-copr-build.yml#L106). If we can manage to keep log files for each package and just appending to it, we can have a daily job that just adds the last logs. I wonder if we want to just make these log files part of the git- repository.

**Comment by kwk** [comment]
This is a screenshot of what I currently have locally and what I've shown to @nikic 

The change is that colors and markers are used to visualize the chroot in which a build was done.

![Bildschirmfoto vom 2023-10-06 14-58-47](https://github.com/kwk/llvm-daily-fedora-rpms/assets/193408/c20e77c1-3183-41f0-b5d8-8b4096fec5f9)

**Comment by kwk** [comment]
The build stats (https://github.com/kwk/llvm-daily-fedora-rpms/blob/gh-pages/build-stats.csv) and diagrams are updated every night at 23:00 and can be accessed here: https://kwk.github.io/llvm-daily-fedora-rpms/ . This way we keep old data around even if copr might no longer have it.
